// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtIrhCTvwWnNZkTeTL5omKinDpfFKEZfA',
    appId: '1:1087503297947:web:0e6f362912d5aced88053e',
    messagingSenderId: '1087503297947',
    projectId: 'vinu-my-notes',
    authDomain: 'vinu-my-notes.firebaseapp.com',
    storageBucket: 'vinu-my-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgE-obMxE2oLSp829T771Mvn8eh6nFgLU',
    appId: '1:1087503297947:android:6e733fc04992bda988053e',
    messagingSenderId: '1087503297947',
    projectId: 'vinu-my-notes',
    storageBucket: 'vinu-my-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGKkmgYIkPKS4rZzXekbV3BkNgPRhvXE',
    appId: '1:1087503297947:ios:7a82fc24e79249af88053e',
    messagingSenderId: '1087503297947',
    projectId: 'vinu-my-notes',
    storageBucket: 'vinu-my-notes.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaGKkmgYIkPKS4rZzXekbV3BkNgPRhvXE',
    appId: '1:1087503297947:ios:5538084cc1fdf09888053e',
    messagingSenderId: '1087503297947',
    projectId: 'vinu-my-notes',
    storageBucket: 'vinu-my-notes.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
